---
name: Lint PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  trigger:
    uses: statnett/workflows/.github/workflows/lint-pr.yml@main
    permissions:
      pull-requests: write
      statuses: write
