---
name: Main
on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: read
jobs:
  build-push-image:
    if: ${{ github.repository == 'statnett/k3a-lag-exporter' }}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-image.yml
    with:
      push: true
