---
name: Release Please
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger:
    uses: statnett/workflows/.github/workflows/release-please.yml@main
    with:
      release-type: maven
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
